query GetPeople {
  getPeople {
    id
    fullName
    gender
    phone
    dateOfBirth
    website
    email
  }
}
query GetPerson($personId: String!) {
  getPerson(id: $personId) {
    id
    fullName
    gender
    phone
    dateOfBirth
    website
    email
    address {
      room
      apartment
      wing
      street
      landmark
      locality
      suburb
      city
      zip
      state
      country
      location {
        plusCode
        coordinates {
          latitude
          longitude
        }
      }
      residents {
        fullName
        email
      }
    }
    demographics {
      salutation
      firstName
      middleName
      lastName
      nickname
    }
    identifications {
      type
      number
      name
      validity {
        start
        end
      }
    }
    socialConnections {
      name
      url
    }
  }
}
mutation CreatePerson($createInput: PersonInput!) {
  createPerson(person: $createInput) {
    id
    fullName
    gender
    phone
    dateOfBirth
    website
    email
  }
}
mutation UpdatePerson($personId: String!, $updateInput: PersonInput!) {
  updatePerson(id: $personId, person: $updateInput) {
    id
    fullName
    gender
    phone
    dateOfBirth
    website
    email
  }
}
mutation DeletePerson($personId: String!) {
  deletePerson(id: $personId) {
    fullName
  }
}
