export {
  Address,
  AddressRelationship,
  AddressRelationshipData,
  Coordinates,
  CoordinatesRelationship,
  CoordinatesRelationshipData,
  Demographics,
  DemographicsRelationship,
  DemographicsRelationshipData,
  Identification,
  IdentificationRelationship,
  IdentificationRelationshipData,
  Location,
  LocationRelationship,
  LocationRelationshipData,
  SocialConnection,
  SocialConnectionRelationship,
  SocialConnectionRelationshipData,
  Tenure,
  TenureRelationship,
  TenureRelationshipData,
  Timezone,
  TimezoneRelationship,
  TimezoneRelationshipData,
  Person
} from '@itinerary-assistant/domain';
