export {
  IAddress,
  ICoordinates,
  IIdentification,
  ILocation,
  IUserDemographics,
  IPhoto,
  ISocialConnection,
  ITenure,
  ITimezone,
  IUser,
  Address,
  Coordinates,
  Gender,
  Identification,
  Location,
  UserDemographics,
  Photo,
  SocialConnection,
  Tenure,
  Timezone
} from '@itinerary-assistant/shared/domain';
