query GetAddress($addressId: String!) {
  getAddress(id: $addressId) {
    id
    room
    apartment
    wing
    street
    landmark
    locality
    suburb
    city
    zip
    state
    country
    addressType
    residents {
      fullName
      email
    }
  }
}

mutation CreateAddress($createInput: AddressInput!) {
  createAddress(address: $createInput) {
    id
    room
    apartment
    wing
    street
    landmark
    locality
    suburb
    city
    zip
    state
    country
    addressType
  }
}

mutation UpdateAddress($addressId: String!, $updateInput: AddressInput!) {
  updateAddress(id: $addressId, address: $updateInput) {
    id
    room
    apartment
    wing
    street
    landmark
    locality
    suburb
    city
    zip
    state
    country
    addressType
  }
}

mutation DeleteAddress($addressId: String!) {
  deleteAddress(id: $addressId) {
    apartment
    street
    city
    zip
    addressType
  }
}
